runtime: go111

handlers:
- url: /media
  static_dir: media
  secure: always

- url: /.*
  script: auto
  secure: always

env_variables:
  SENDGRID_API_KEY: "put key here"
  SENDER_ADDRESS: "*** sender address ***"
  BCC_ADDRESS: "*** bcc address ***"
  ERROR_ADDRESS: "*** error address ***"
  GOOGLE_WALLET_ADDRESS: "..."
  VENMO_ADDRESS: "..."
  PAYPAL_ADDRESS: "..."
  PAYPAL_URL: "https://www.paypal.com/"
