runtime: go122

handlers:
- url: /media
  static_dir: media
  secure: always

- url: /.*
  script: auto
  secure: always

env_variables:
  SENDGRID_API_KEY: "*** REPLACE ***"
  SENDER_ADDRESS: "chrisanddana@shabsin.com"
  BCC_ADDRESS: "psr-mail@googlegroups.com"
  ERROR_ADDRESS: "chrisanddana@shabsin.com"
  GOOGLE_WALLET_ADDRESS: "dana.m.scott@gmail.com"
  VENMO_ADDRESS: "@Chris-Shabsin"
  PAYPAL_ADDRESS: "cshabsin@gmail.com"
  PAYPAL_URL: "https://www.paypal.com/"

app_engine_apis: true
