runtime: go
api_version: go1

handlers:
- url: /media
  static_dir: media
  secure: always

- url: /.*
  script: _go_app
  secure: always

env_variables:
  SENDGRID_API_KEY: "put key here"
  SENDER_ADDRESS: "*** sender address ***"
  BCC_ADDRESS: "*** bcc address ***"
  ERROR_ADDRESS: "*** error address ***"